# Generated by Django 2.1.7 on 2019-08-06 23:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDectection',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('cords', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
